### ISSUE TITLE
Create endpoints for getting events

### ISSUE THREAD

**Issue by jasozh** [cornellh4i/lagos-volunteers#10]
### Goal: to create endpoints for getting all events that meet some sort of filter/criteria
**Branch name:** `get-events`

### Task at Hand
1. View the API documentation on our Notion page
2. Open `events/views.ts` and define the following endpoints: `/events/all`, `/events/upcoming/`, `/events/current`, and `/events/past`. The endpoint responses should follow the status codes written in the API documentation.
3. Open `events/controllers.ts` and write functions to implement your endpoints. Write detailed specifications for every function and comment your code where necessary.
4. Update the Swagger file with your API changes
5. Write at least 2 Jest tests for each endpoint

### Action Items
- [ ] Create the `/events/all` endpoint
- [ ] Create the `/events/upcoming` endpoint
- [ ] Create the `/events/current` endpoint
- [ ] Create the `/events/past` endpoint
- [ ] Update Swagger
- [ ] Write test cases
