### ISSUE TITLE
Create endpoints for creating, editing, and deleting users

### ISSUE THREAD

**Issue by jasozh** [cornellh4i/lagos-volunteers#11]
### Goal: to create endpoints for creating, editing, and deleting users
**Branch name:** `change-users`

### Task at Hand
1. View the API documentation on our Notion page
2. Open `user/views.ts` (NOT `users/views.ts`) and define the following endpoints: `/user/create`, `/user/delete/`, and `/user/update`. The endpoint responses should follow the status codes written in the API documentation.
3. Open `user/controllers.ts` and write functions to implement your endpoints. Write detailed specifications for every function and comment your code where necessary.
4. Update the Swagger file with your API changes
5. Write at least 2 Jest tests for each endpoint

### Action Items
- [x] Implement the `/user/create` endpoint
- [x] Implement the `/user/delete` endpoint
- [x] Implement the `/user/update` endpoint
- [x] Update Swagger
- [x] Write test cases
