### ISSUE TITLE
Implement About Page (frontend)

### ISSUE THREAD

**Issue by jasozh** [cornellh4i/lagos-volunteers#111]
**Branch:** `about-page-frontend`

### Task at Hand
1. View the [mid-fidelity designs](https://www.figma.com/file/58CoTkFT4TgalsOyc1Patl/%F0%9F%8C%BE-Lagos-Food-Bank?type=design&node-id=1809-21467&mode=design&t=QD3MBT6azmzjOBjZ-0) for the **Admin Edit Website Metadata Flow** pages.
2. Implement the `About` component following the acceptance criteria below.

### Acceptance Criteria
- [ ] Users can see the `About` component with placeholder text in the format of the Figma file.
- [ ] Users can click an edit button which transforms the content of the page into a rich text box that enables typing text, bold/italicized text, and bullet points. The edit button should then be transformed into a save button.
- [ ] After saving their changes, the new page should reflect the changes made in the edit box.

### Notes
- We will need a **rich text editor**. Just using a textbox is not sufficient since it doesn't provide any formatting. The best one I found  is [react-quill](https://github.com/zenoamaro/react-quill). Look into its documentation and see an example [here](https://codesandbox.io/s/react-playground-luctk?file=/src/components/QuillEditor/Editor.jsx).
- Do **not** worry about the cards in the Figma file. Just focus on implementing the text section.
- Use `useState` to save the existing text information. Saving the button should have the page look like the new update (since the updates are saved in a `useState` variable), but refreshing the page will reset the content since we don't make any calls to the backend yet.
