### ISSUE TITLE
Implement searching, sorting, and pagination (backend)

### ISSUE THREAD

**Issue by jasozh** [cornellh4i/lagos-volunteers#114]
**Branch:** `events-users-backend`

### Task at Hand

1. Open `/backend/src/users/views.ts` and `/backend/src/events/views.ts`.
2. Implement the acceptance criteria.
3. Confirm that your code and pull request follow the [Pull Request Checklist](https://www.notion.so/h4i/Pull-Request-Checklist-910d5e6925df49569067f00f6aa0c0f3).

### Acceptance Criteria

- [x] `GET /users` is an endpoint that combines searching, sorting and pagination. For example, `GET /api/users?firstName="Bobby"&lastName="Fischer"&sort=email:asc&limit=100&after=xjf48992` should be a valid API endpoint that gets the first 100 users with name "Bobby Fischer" sorted by email in ascending order.
- [x] `GET /events` is an endpoint that combines sorting and pagination. For example, `GET /api/events/upcoming=true?sort=location:desc&limit=20&after=xjf48992` should be a valid API endpoint that gets the first 20 upcoming events sorted by location in descending order.
- [x] All of the sorting and pagination from `GET /users` and `GET /events` should be applicable to any API endpoint that returns similar functionality. The following endpoints should be implemented: `GET /users/:userid/created`, `GET /users/:userid/registered`, `GET /events/:eventid/attendees`.

### Notes

- View the [API documentation](https://www.notion.so/h4i/API-Documentation-956584fab90649f889094520153317f4) to understand how we are doing pagination, sorting, and searching.
- Each of these functions should already be implemented individually. Take a look at the controllers file for both `users` and `events` to see existing implementations. This ticket should be **combining** the functionality from these functions; you shouldn't have to write it anew.
