### ISSUE TITLE
Implement Create Event (fullstack)

### ISSUE THREAD

**Issue by jasozh** [cornellh4i/lagos-volunteers#118]
**Branch:** `create-event-fullstack`

### Task at Hand

1. View the [mid-fidelity designs](https://www.figma.com/file/58CoTkFT4TgalsOyc1Patl/%F0%9F%8C%BE-Lagos-Food-Bank?type=design&node-id=1809-21467&mode=design&t=QD3MBT6azmzjOBjZ-0) for the Create Event pages.
2. Open the `EventForm` component.
3. Implement the component with the acceptance criteria below.
4. Confirm that your code and pull request follow the [Pull Request Checklist](https://www.notion.so/h4i/Pull-Request-Checklist-910d5e6925df49569067f00f6aa0c0f3).

### Acceptance Criteria

- [x] Users can successfully create an event by pressing the **Create Event** button.
- [x] Users who are editing an event will see event details already prepopulated in the form.
- [x] Users can successfully modify an event by pressing the **Save Changes** button.
- [x] The **RSVP Link Preview** must show the correct link for volunteers to register. This should be in the format `[base url]/events/[event id]/register`.

### Notes

- Use the following API endpoints: `GET /events/:eventid`, `POST /events`, and `PUT /events/:eventid`. See the [API documentation](https://www.notion.so/h4i/API-Documentation-956584fab90649f889094520153317f4) for more detail.
