### ISSUE TITLE
Implement Manage User Profile (fullstack)

### ISSUE THREAD

**Issue by jasozh** [cornellh4i/lagos-volunteers#121]
**Branch:** `manage-user-pofile-fullstack`

### Task at Hand

1. View the [mid-fidelity designs](https://www.figma.com/file/58CoTkFT4TgalsOyc1Patl/%F0%9F%8C%BE-Lagos-Food-Bank?type=design&node-id=1809-21467&mode=design&t=QD3MBT6azmzjOBjZ-0) for the Manage Users pages.
2. Open the `UserProfile` component.
3. Implement the component with the acceptance criteria below.
4. Confirm that your code and pull request follow the [Pull Request Checklist](https://www.notion.so/h4i/Pull-Request-Checklist-910d5e6925df49569067f00f6aa0c0f3).

### Acceptance Criteria

- [x] The `UserProfile` component is correctly populated with the details of that user.
- [x] The **Status**, **Registrations**, and **Verify Certificate Request** page show the correct data for the given user.
- [ ] Admins can assign roles for users, changing a user's role between Volunteer, Supervisor, and Admin.
- [ ] Admins can blacklist users and remove them from the blacklist.

### Notes

- Use the following API endpoints: `GET /users/:userid`, `PATCH /users/:userid/status`, and `PATCH /users/:userid/role`. See the [API documentation](https://www.notion.so/h4i/API-Documentation-956584fab90649f889094520153317f4) for more detail.
- For the registration tab, just use `GET /events` to populate the table with event data. We will replace it with our actual API endpoint once that's finished.
- Do **not** implement the Verify Certificate Request button.
