### ISSUE TITLE
Verify email after signup (fullstack)

### ISSUE THREAD

**Issue by jasozh** [cornellh4i/lagos-volunteers#156]
**Branch:** `verify-email-fullstack`

### Task at Hand

1. Implement your code in `/frontend/src/components/organisms/SignupForm.tsx` and the `createUser` function in `/backend/src/users/controllers.ts`.
2. Confirm that your code and pull request follow the [Pull Request Checklist](https://www.notion.so/h4i/Pull-Request-Checklist-910d5e6925df49569067f00f6aa0c0f3).

### Acceptance Criteria

- [x] After signing up, users first receive an email in their inbox with a unique link. Clicking this link verifies their email and allows them to sign in.
- [x] Users should be able to resend the verification email.
- [x] Users should not be able to sign in until their email has been verified.
- [ ] ~Users who have signed up but have not verified their email should have their account eventually removed.~

### Notes

- See this Firebase blog post [here](https://firebase.blog/posts/2017/02/email-verification-in-firebase-auth/).

This is the flow for user registration
- Users sign in using the sign up form. This creates a new user with credentials in our database and Firebase.
- Users are then redirected to a page with the text "Please refresh this page once you have verified your email."
- Users are stuck on this page until they click a unique link from their email.
