### ISSUE TITLE
Reset password page (fullstack)

### ISSUE THREAD

**Issue by jasozh** [cornellh4i/lagos-volunteers#168]
**Branch:** `reset-password-fullstack`

### Task at Hand

1. Implement your code in the `ResetPasswordForm` component.
2. Confirm that your code and pull request follow the [Pull Request Checklist](https://www.notion.so/h4i/Pull-Request-Checklist-910d5e6925df49569067f00f6aa0c0f3).

### Acceptance Criteria

- [x] Users should be reset their password on our website rather than through the Firebase prompt.
- [x] The reset password email should have a custom link that points towards our website.
- [x] This should be secure.

### Notes

- Reach out to Akin to update the firebase console for the page you use for testing
