### ISSUE TITLE
Role specific pages (fullstack)

### ISSUE THREAD

**Issue by jasozh** [cornellh4i/lagos-volunteers#169]
**Branch:** `roles-fullstack`

### Task at Hand

1. Implement your code in `AuthContext.tsx` and any other files necessary.
2. Confirm that your code and pull request follow the [Pull Request Checklist](https://www.notion.so/h4i/Pull-Request-Checklist-910d5e6925df49569067f00f6aa0c0f3).

### Acceptance Criteria

- [x] Volunteers should be able to only access the pages they have access to.
- [x] Supervisors should be able to only access the pages they have access to.
- [x] Admins should be able to only access the pages they have access to.
- [x] When a user’s role is changed, update their Firebase custom claim (see `ManageUserProfile.tsx`)

### Notes

- Use Firebase custom tokens to check the role of the user and see whether they are volunteers, supervisors, or admins. Only allow users with the necessary permission to view specific pages.
- Supervisors only: Manage Event, Create/Edit Event, View Events (only part of the website)
- Admins: Manage Website (not implemented yet), Manage Members, FAQ page (only part of the webiste)
