### ISSUE TITLE
Setup Firebase authentication for login and signup

### ISSUE THREAD

**Issue by jasozh** [cornellh4i/lagos-volunteers#20]
### Goal: to setup Firebase authentication for login and signup
**Branch name:** `firebase-auth`

### Task at Hand
1. Login to [Firebase Console](https://console.firebase.google.com) with your provided account credentials.
2. Navigate to **Project settings > Service accounts** in Firebase Console and copy the Admin SDK configuration snippet. Paste the snippet in `/backend/src/server.ts` and change `var` to `const` for all variables.
3. Replace `serviceAccount` with the following object:
    <br>
    ```ts
    const serviceAccount = {
	    type: process.env.TYPE,
	    project_id: process.env.PROJECT_ID,
	    private_key_id: process.env.PRIVATE_KEY_ID,
	    private_key: process.env.PRIVATE_KEY.replace(/\\n/g, ‘\n’),
	    client_email: process.env.CLIENT_EMAIL,
	    client_id: process.env.CLIENT_ID,
	    auth_uri: process.env.AUTH_URI,
	    token_uri: process.env.TOKEN_URI,
	    auth_provider_x509_cert_url: process.env.AUTH_PROVIDER_x509_CERT_URL,
	    client_x509_cert_url: process.env.CLIENT_x509_CERT_URL,
    };
    ```
5. If you haven't already, use `yarn` to install the `firebase-admin` package. Make sure you commit `package.json` so that your dependency is included in your pull request.
6. Open `/backend/.env` and define variables for all of the `process.env.VARNAME` variables shown above. Use your provided `serviceAccountCredentials.json` file to fill in the values for each key.
7. Create the file `/backend/src/middleware/auth.ts`.
8. Read the Firebase documentation on [Verify ID Tokens](https://firebase.google.com/docs/auth/admin/verify-id-tokens) and [Control Access with Custom Claims](https://firebase.google.com/docs/auth/admin/custom-claims). Also, read this [Stack Overflow post](https://stackoverflow.com/questions/64205096/using-firebase-as-an-authenticating-middleware-in-express-js). Now, implement the following functions:
    <br>
    ```
    /** Retrieves a token from Firebase */
    getAuthToken
    
    /** Authorizes a request if a token is present, returning an error otherwise. */
    auth
    
    /** Authorizes a request if a token is present with the volunteer claim, returning an error otherwise. */
    authIfVolunteer
    
    /** Authorizes a request if a token is present with the supervisor claim, returning an error otherwise. */
    authIfSupervisor
    
    /** Authorizes a request if a token is present with the admin claim, returning an error otherwise. */
    authIfAdmin
    ```
9. Pass authentication into all of the endpoints appropriately so that an auth token is needed for an API call.
10. Find a way to test the endpoints to make sure that they work if an auth token is passed in.
11. Read the Firebase documentation on [Manage Users](https://firebase.google.com/docs/auth/admin/manage-users). Modify the endpoints `GET /users/:userid` and `POST /users/` so that they retrieve/create a user in Firebase in addition to our database.
12. Confirm that your code and pull request follow the [Pull Request Checklist](https://h4i.notion.site/Pull-Request-Checklist-37c67d3b6a9b488f8339f32116bfb12c).

### Action Items
- [x] Configure the Firebase Admin SDK.
- [x] Implement the authentication middleware.
- [x] Pass authentication into the appropriate endpoints.
- [x] Modify the existing endpoints.
- [x] Test your functionality.
