### ISSUE TITLE
Log in with Google (fullstack)

### ISSUE THREAD

**Issue by jasozh** [cornellh4i/lagos-volunteers#236]
**Branch:** `login-google-fullstack`

### Task at Hand

1. Implement your code in `frontend/src/components/organisms/LoginForm.tsx`.
2. Confirm that your code and pull request follow the [Pull Request Checklist](https://www.notion.so/h4i/Pull-Request-Checklist-910d5e6925df49569067f00f6aa0c0f3).

### Acceptance Criteria

- [x] Users should be able to use the **Continue with Google** button on the login page to sign in with their Google account.
- [x] If the user email does not already exist in the system, doing a Google sign in should create a new user account. There should be no need to send a password verification email since Google is a trusted source, so the user should already be set to verified.
- [x] If the user email does exist in the system, doing a Google sign in should act as a log in. Users should be able to sign in with both their email and password, and the auth providers should be linked.

### Notes

- See the Firebase documentation for Google authentication [here](https://firebase.google.com/docs/auth/web/google-signin).
- See the documentation for linking auth providers [here](https://firebase.google.com/docs/auth/web/account-linking).
- Maybe [this](https://blog.bitsrc.io/firebase-authentication-with-react-for-beginners-implementing-email-password-and-google-sign-in-e62d9094e22) is helpful.
