### ISSUE TITLE
Event cancel (fullstack)

### ISSUE THREAD

**Issue by jasozh** [cornellh4i/lagos-volunteers#238]
**Branch:** `event-cancel-fullstack`

### Task at Hand

1. Implement the acceptance criteria.
2. Confirm that your code and pull request follow the [Pull Request Checklist](https://www.notion.so/h4i/Pull-Request-Checklist-910d5e6925df49569067f00f6aa0c0f3).

### Acceptance Criteria

- [ ] When a supervisor clicks on the **Cancel Event** button in the Edit Event form, the event status should be set to canceled.
- [ ] When an event is canceled, the **Cancel Event** and **Save changes** button should be grayed out.
- [ ] When the current datetime is past the end datetime of the event, the **Cancel Event** and **Save changes** button should be grayed out.

### Notes

- You will need to write a new controller + endpoint.
