### ISSUE TITLE
Show check-in status (fullstack)

### ISSUE THREAD

**Issue by jasozh** [cornellh4i/lagos-volunteers#252]
**Branch:** `show-check-in-fullstack`

### Task at Hand

1. Implement the acceptance criteria.
2. Confirm that your code and pull request follow the [Pull Request Checklist](https://www.notion.so/h4i/Pull-Request-Checklist-910d5e6925df49569067f00f6aa0c0f3).

### Acceptance Criteria

- [ ] When volunteers click on the **Past Events** tab in the My Events page, each event should show the volunteer's event registration status (whether the user is pending, checked in, checked out, etc.)
- [ ] Upcoming events should be sorted by datetime such that the oldest event is at the top.
- [ ] Past events should be sorted by datetime such that the latest event is at the top.

### Notes

- Lorem ipsum.
