### ISSUE TITLE
Implement login functionality

### ISSUE THREAD

**Issue by jasozh** [cornellh4i/lagos-volunteers#51]
**Branch:** `login-fullstack`

### Task at Hand
1. Open the `LoginForm` component.
2. Implement the `Sign Up with Email` button (navigation only), the `Log in` button, and the `Forgot Password` button (navigation only).
4. Confirm that your code and pull request follow the [Pull Request Checklist](https://h4i.notion.site/Pull-Request-Checklist-37c67d3b6a9b488f8339f32116bfb12c).

### Acceptance Criteria
- [ ] Users can navigate to the Signup page.
- [ ] Users can use their email address and password to log in to the website. On a successful login request, the user should be redirected to the View Events page, and all API requests should now be authorized using the retrieved Firebase token.
- [ ] Users can navigate to the Forgot Password page.

### Notes
- Don't implement the `Continue with Google` button. This will be part of a future ticket.
- Login functionality is actually already implemented in the placeholder component `Login.tsx`. Take a look at this file and use it when implementing our website's actual login functionality.
