### ISSUE TITLE
Implement view/edit profile functionality

### ISSUE THREAD

**Issue by jasozh** [cornellh4i/lagos-volunteers#53]
**Branch:** `profile-fullstack`

### Task at Hand
1. Open the `ProfileForm` component.
2. Implement the `Cancel` button and the `Save changes` button.
4. Confirm that your code and pull request follow the [Pull Request Checklist](https://h4i.notion.site/Pull-Request-Checklist-37c67d3b6a9b488f8339f32116bfb12c).

### Acceptance Criteria
- [x] Users can see their account and profile information prepopulated in the form.
- [ ] Users can update their profile information and save changes. Updates should be propagated to both the SQL database and Firebase. When the form is opened up, the user's existing data should already be prepopulated in the form.
- [x] Users can use the `Cancel` button to return to the View Events page.
