### ISSUE TITLE
Create endpoints for getting users

### ISSUE THREAD

**Issue by jasozh** [cornellh4i/lagos-volunteers#9]
### Goal: to create endpoints for getting all users that meet some sort of filter/criteria
**Branch name:** `get-users`

### Task at Hand
1. View the API documentation on our Notion page
2. Open `users/views.ts` and define the following endpoints: `/users/all` and `/users/search`. The endpoint responses should follow the status codes written in the API documentation.
3. Open `users/controllers.ts` and write functions to implement your endpoints. Write detailed specifications for every function and comment your code where necessary.
4. Update the Swagger file with your API changes
5. Write at least 2 Jest tests for each endpoint

View [this link](https://www.soapui.org/learn/api/understanding-rest-headers-and-parameters/) to find more information on query search parameters.

### Action Items
- [x] Create the `/users/all` endpoint
- [x] Create the `/users/search` endpoint
- [ ] Update Swagger
- [x] Write test cases
